# Generated by Django 5.0.2 on 2024-02-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldoctorappointments',
            name='consultation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicify_project.tblconsultations'),
        ),
        migrations.AlterField(
            model_name='tblprescriptions',
            name='consultation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicify_project.tblconsultations'),
        ),
        migrations.CreateModel(
            name='ConsultationFee',
            fields=[
                ('consultation_fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_type', models.IntegerField()),
                ('first_visit_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('second_visit_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultaion_fee_doctor_id', to='medicify_project.tbldoctors')),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultaion_fee_location_id', to='medicify_project.tbldoctorlocations')),
            ],
            options={
                'db_table': 'consultation_fee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicalServicesFee',
            fields=[
                ('medical_service_fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.IntegerField()),
                ('charges', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_doctor_id', to='medicify_project.tbldoctors')),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_location_id', to='medicify_project.tbldoctorlocations')),
            ],
            options={
                'db_table': 'medical_services_fee',
                'managed': True,
            },
        ),
    ]
