# Generated by Django 5.0.2 on 2024-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0002_alter_tbldoctorappointments_consultation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpatientfindingsandsymtoms',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblpatientfindingsandsymtoms',
            name='kco',
            field=models.CharField(blank=True, null=True),
        ),
    ]
