# Generated by Django 5.0.2 on 2024-02-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0003_tblpatientfindingsandsymtoms_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconsultations',
            name='consultation_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tblconsultations',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblconsultations',
            name='referred_to_doctor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
