# Generated by Django 5.0.2 on 2024-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0004_tblconsultations_consultation_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoctorappointments',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblpatientvitals',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbldoctormedicines',
            name='medicine_dosages',
            field=models.CharField(max_length=100),
        ),
    ]
