# Generated by Django 5.0.2 on 2024-02-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0005_tbldoctorappointments_age_tblpatientvitals_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatacodemaster',
            name='datacodename',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tbldatacodemaster',
            name='datacodevalue',
            field=models.CharField(max_length=256),
        ),
    ]
