# Generated by Django 5.0.2 on 2024-02-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0007_tblconsultations_referred_by_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbllabinvestigations',
            fields=[
                ('investigation_id', models.AutoField(primary_key=True, serialize=False)),
                ('investigation_category', models.CharField(max_length=255)),
                ('investigation_name', models.CharField(max_length=255)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('createdon', models.IntegerField(blank=True, null=True)),
                ('lastmodifiedon', models.IntegerField(blank=True, null=True)),
                ('lastmodifiedby', models.IntegerField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(blank=True, default='0', null=True)),
                ('deletedby', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicify_project.tbldoctors')),
            ],
            options={
                'db_table': 'Tbllabinvestigations',
            },
        ),
        migrations.AlterField(
            model_name='tblpatientlabinvestigations',
            name='patient_labtestid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicify_project.tbllabinvestigations'),
        ),
    ]
