# Generated by Django 5.0.2 on 2024-02-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0008_tbllabinvestigations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbllabinvestigations',
            name='age',
        ),
    ]
