# Generated by Django 5.0.2 on 2024-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0009_remove_tbllabinvestigations_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldoctorlocations',
            name='location_token',
        ),
        migrations.AddField(
            model_name='tbldoctorlocations',
            name='unique_location_token_constraint',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
