# Generated by Django 5.0.2 on 2024-03-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0010_remove_tbldoctorlocations_location_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldoctorlocations',
            old_name='unique_location_token_constraint',
            new_name='location_token',
        ),
    ]
