# Generated by Django 5.0.2 on 2024-03-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0012_tblchatscripts_tblscriptoptions_tbluseractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationfee',
            name='avg_time_per_patient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationfee',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationfee',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbldoctorlocations',
            name='services_offered_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbldoctors',
            name='additional_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbldoctors',
            name='basic_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbldoctors',
            name='services_offered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
