# Generated by Django 5.0.2 on 2024-03-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0014_tbldoctorleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconsultations',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
