# Generated by Django 5.0.2 on 2024-03-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0015_tblconsultations_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpatientmedications',
            name='medicine_doses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
