# Generated by Django 5.0.2 on 2024-03-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0017_tblpatientvitals_appointment_id_tblpatientvitals_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoctormedicines',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbldoctormedicines',
            name='medicine_preservation',
            field=models.CharField(max_length=256),
        ),
    ]
