# Generated by Django 5.0.2 on 2024-04-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0018_tbldoctormedicines_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblchatscripts',
            name='Location_token',
        ),
        migrations.RemoveField(
            model_name='tblscriptoptions',
            name='Location_token',
        ),
        migrations.RemoveField(
            model_name='tblscriptoptions',
            name='Script_Code',
        ),
    ]
