# Generated by Django 5.0.2 on 2024-04-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0019_remove_tblchatscripts_location_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbluseractions',
            name='Location_token',
        ),
        migrations.RemoveField(
            model_name='tbluseractions',
            name='Script_Code',
        ),
    ]
