# Generated by Django 5.0.2 on 2024-04-03 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0020_remove_tbluseractions_location_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblchatscripts',
            name='Location_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicify_project.tbldoctorlocations', to_field='location_token'),
        ),
        migrations.AddField(
            model_name='tblscriptoptions',
            name='Location_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicify_project.tbldoctorlocations', to_field='location_token'),
        ),
        migrations.AddField(
            model_name='tblscriptoptions',
            name='Script_Code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicify_project.tblchatscripts'),
        ),
        migrations.AddField(
            model_name='tbluseractions',
            name='Location_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicify_project.tbldoctorlocations', to_field='location_token'),
        ),
        migrations.AddField(
            model_name='tbluseractions',
            name='Script_Code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicify_project.tblchatscripts'),
        ),
    ]
