# Generated by Django 5.0.2 on 2024-04-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0021_tblchatscripts_location_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconsultations',
            name='consultation_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
