# Generated by Django 5.0.1 on 2024-04-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0022_tblconsultations_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoctorlocations',
            name='location_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
    ]
