# Generated by Django 5.0.1 on 2024-05-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0023_tbldoctorlocations_location_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblUsers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_mobileno', models.CharField(max_length=10)),
                ('user_login_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('user_role', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location_id', to='medicify_project.tbldoctorlocations')),
            ],
            options={
                'db_table': 'tblUsers',
            },
        ),
    ]
