# Generated by Django 5.0.1 on 2024-05-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0024_tblusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpatients',
            name='follower',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
