# Generated by Django 5.0.1 on 2024-05-29 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0025_tblpatients_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatacodemaster',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tbldatacodemaster_doctor_id', to='medicify_project.tbldoctors'),
        ),
    ]
