# Generated by Django 5.0.1 on 2024-06-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0027_tblmasterallergies_tblmasterdisease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblPatientDoctorLink',
            fields=[
                ('patientdoctorlink_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_approval', models.CharField(default='yes', max_length=10)),
                ('link_reject_reason', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientdoctorlink_doctor_id', to='medicify_project.tbldoctors')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientdoctorlink_patient_id', to='medicify_project.tblpatients')),
            ],
            options={
                'db_table': 'tblPatientDoctorLink',
            },
        ),
    ]
