# Generated by Django 5.0.1 on 2024-06-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0029_tblpatientdoctorlink_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionSettings',
            fields=[
                ('prescriptionsettings_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_size', models.IntegerField(blank=True, null=True)),
                ('clinic_logo_alignment', models.IntegerField(blank=True, null=True)),
                ('header_type', models.IntegerField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('header_top_margin', models.FloatField(blank=True, null=True)),
                ('clinic_name', models.IntegerField(default=0)),
                ('clinic_address', models.IntegerField(default=0)),
                ('doctor_name', models.IntegerField(default=0)),
                ('doctor_degree', models.IntegerField(default=0)),
                ('doctor_speciality', models.IntegerField(default=0)),
                ('doctor_availability', models.IntegerField(default=0)),
                ('clinic_services', models.IntegerField(default=0)),
                ('clinic_logo', models.IntegerField(default=0)),
                ('clinic_mobile_number', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_doctor_id', to='medicify_project.tbldoctors')),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_location_id', to='medicify_project.tbldoctorlocations')),
            ],
            options={
                'db_table': 'prescription_settings',
            },
        ),
    ]
