# Generated by Django 5.0.1 on 2024-07-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0030_prescriptionsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('franchise_id', models.IntegerField(blank=True, default=0, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_email', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_dob', models.BigIntegerField(blank=True, null=True)),
                ('lead_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('lead_source', models.IntegerField(blank=True, null=True)),
                ('lead_product', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('lead_status', models.IntegerField(blank=True, default=1, null=True)),
                ('lead_date_time_stamp', models.BigIntegerField(blank=True, null=True)),
                ('lead_by_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('lead_department', models.IntegerField(blank=True, null=True)),
                ('crm_ref_id', models.IntegerField(blank=True, default=0, null=True)),
                ('lead_stage', models.IntegerField(blank=True, default=1, null=True)),
                ('lead_city', models.IntegerField(blank=True, null=True)),
                ('lead_handler_id', models.IntegerField(blank=True, null=True)),
                ('lead_handler_type', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('lead_followup_old_status', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('lead_month_year', models.CharField(blank=True, max_length=50, null=True)),
                ('app_id', models.IntegerField(blank=True, default=2, null=True)),
            ],
            options={
                'db_table': 'tblLeads',
            },
        ),
        migrations.CreateModel(
            name='TblLeadFollowUp',
            fields=[
                ('follow_up_id', models.AutoField(primary_key=True, serialize=False)),
                ('follow_up_date_time_stamp', models.BigIntegerField(blank=True, null=True)),
                ('follow_up_method', models.IntegerField(blank=True, null=True)),
                ('follow_up_details', models.TextField(blank=True, null=True)),
                ('follow_up_success_status', models.IntegerField(blank=True, null=True)),
                ('follow_up_activity', models.IntegerField(blank=True, default=0, null=True)),
                ('next_follow_up_date_time_stamp', models.BigIntegerField(blank=True, null=True)),
                ('next_follow_up_method', models.IntegerField(blank=True, null=True)),
                ('next_follow_up_action', models.TextField(blank=True, null=True)),
                ('follow_up_by', models.IntegerField(blank=True, null=True)),
                ('follow_up_user_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('by_department', models.IntegerField(blank=True, default=0, null=True)),
                ('app_id', models.IntegerField(blank=True, default=2, null=True)),
                ('lead_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeadFollowUp_lead_id', to='medicify_project.tbllead')),
            ],
            options={
                'db_table': 'tblLeadFollowUp',
            },
        ),
    ]
