# Generated by Django 5.0.1 on 2024-07-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0031_tbllead_tblleadfollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCountries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sortname', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phonecode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblCountries',
            },
        ),
        migrations.CreateModel(
            name='TblStates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='medicify_project.tblcountries')),
            ],
            options={
                'db_table': 'tblStates',
            },
        ),
        migrations.CreateModel(
            name='TblCities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='medicify_project.tblstates')),
            ],
            options={
                'db_table': 'tblCities',
            },
        ),
    ]
