# Generated by Django 5.0.1 on 2024-07-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0032_tblcountries_tblstates_tblcities'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldoctors',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
