# Generated by Django 5.0.1 on 2024-07-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0033_tbldoctors_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpateintcharges',
            name='new_outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblpateintcharges',
            name='previous_outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblpatientpayments',
            name='new_outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblpatientpayments',
            name='previous_outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblpatients',
            name='outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
