# Generated by Django 5.0.1 on 2024-08-02 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0034_tblpateintcharges_new_outstanding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblDoctorSubscriptionPromocodes',
            fields=[
                ('promocode_id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_code_activation_on', models.BigIntegerField(blank=True, null=True)),
                ('promo_code_valid_till', models.BigIntegerField(blank=True, null=True)),
                ('promo_code_value', models.IntegerField(blank=True, null=True)),
                ('promo_code_value_type', models.IntegerField(blank=True, null=True)),
                ('promo_code_status', models.IntegerField(blank=True, null=True)),
                ('entry_operator_id', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_operator_type', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_code_used_by', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_code_used_on', models.BigIntegerField(blank=True, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_doctor_subscription_promocodes',
            },
        ),
        migrations.CreateModel(
            name='TblMasterSubscription',
            fields=[
                ('master_subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_one', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_two', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_trial', models.BooleanField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblmaster_subscription',
            },
        ),
        migrations.CreateModel(
            name='TblDoctorSubscription',
            fields=[
                ('doctor_subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_start_on', models.BigIntegerField(blank=True, null=True)),
                ('subscription_end_on', models.BigIntegerField(blank=True, null=True)),
                ('subscription_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_tax1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_tax2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_discount_type', models.IntegerField(blank=True, null=True)),
                ('subscription_promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_type', models.IntegerField(blank=True, null=True)),
                ('subscription_billing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_billing_GstNo', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_billing_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_billing_city', models.IntegerField(blank=True, null=True)),
                ('subscription_status', models.IntegerField(blank=True, default=0, null=True)),
                ('entry_operator_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_doctor_id', to='medicify_project.tbldoctors')),
                ('master_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorsubscription_mastersubscription_id', to='medicify_project.tblmastersubscription')),
            ],
            options={
                'db_table': 'tbldoctor_subscription',
            },
        ),
    ]
