# Generated by Django 5.0.1 on 2024-08-20 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0035_tbldoctorsubscriptionpromocodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbllead',
            name='lead_added_on',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbllead',
            name='lead_country',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbllead',
            name='lead_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbllead',
            name='lead_sub_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomFCMDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.CharField(blank=True, max_length=250, null=True)),
                ('browser', models.CharField(blank=True, max_length=250, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=255, null=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_devices', to='medicify_project.authuser')),
            ],
            options={
                'db_table': 'CustomFCMDevice',
            },
        ),
        migrations.CreateModel(
            name='NotificationCRM',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_icon', models.FileField(blank=True, max_length=2000, null=True, upload_to='notification/admin_collection_notification_icon/')),
                ('notification_image', models.FileField(blank=True, max_length=2000, null=True, upload_to='notification/admin_collection_notification_image/')),
                ('notification_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_body', models.TextField(blank=True, null=True)),
                ('notification_action', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_send', models.DateTimeField(null=True)),
                ('notification_delivered', models.DateTimeField(null=True)),
                ('notification_read', models.DateTimeField(null=True)),
                ('notification_status', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_collection_notifications_created_by', to='medicify_project.authuser')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_collection_notifications_deleted_by', to='medicify_project.authuser')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_collection_notifications_last_modified_by', to='medicify_project.authuser')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_collection_notification', to='medicify_project.authuser')),
            ],
            options={
                'db_table': 'NotificationCRM',
            },
        ),
    ]
