# Generated by Django 5.0.1 on 2024-09-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0036_tbllead_lead_added_on_tbllead_lead_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblPharmacist',
            fields=[
                ('pharmacist_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('shop_owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_owner_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pharmacist_username', models.CharField(blank=True, max_length=50, null=True)),
                ('pharmacist_password', models.CharField(blank=True, max_length=128, null=True)),
                ('pharmacist_token', models.CharField(blank=True, max_length=32, null=True)),
                ('pharmacist_type', models.IntegerField(blank=True, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblPharmacist',
            },
        ),
        migrations.CreateModel(
            name='tblDoctorPharmacistlink',
            fields=[
                ('doctorpharmacist_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorpharmacist_doctor_id', to='medicify_project.tbldoctors')),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorpharmacist_location_id', to='medicify_project.tbldoctorlocations')),
                ('pharmacist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorpharmacist_pharmacist_id', to='medicify_project.tblpharmacist')),
            ],
            options={
                'db_table': 'tblDoctorPharmacistlink',
            },
        ),
        migrations.CreateModel(
            name='tblPrescribePharmacist',
            fields=[
                ('prescribepharmacist_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionpharmacist_doctor_id', to='medicify_project.tbldoctors')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionpharmacist_patient_id', to='medicify_project.tblpatients')),
                ('pharmacist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionpharmacist_pharmacist_id', to='medicify_project.tblpharmacist')),
                ('prescription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionpharmacist_prescription_id', to='medicify_project.tblprescriptions')),
            ],
            options={
                'db_table': 'tblPrescribePharmacist',
            },
        ),
    ]
