# Generated by Django 5.0.1 on 2024-10-09 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0038_tblprescribepharmacist_pharma_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblLaboratory',
            fields=[
                ('laboratory_id', models.AutoField(primary_key=True, serialize=False)),
                ('laboratory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratory_address', models.CharField(blank=True, max_length=255, null=True)),
                ('laboratory_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('laboratory_owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratory_owner_number', models.CharField(blank=True, max_length=15, null=True)),
                ('laboratory_username', models.CharField(blank=True, max_length=50, null=True)),
                ('laboratory_password', models.CharField(blank=True, max_length=128, null=True)),
                ('laboratory_token', models.CharField(blank=True, max_length=32, null=True)),
                ('laboratory_type', models.IntegerField(blank=True, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblLaboratory',
            },
        ),
        migrations.CreateModel(
            name='tblDoctorLaboratorylink',
            fields=[
                ('doctorlaboratory_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorlaboratory_doctor_id', to='medicify_project.tbldoctors')),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorlaboratory_location_id', to='medicify_project.tbldoctorlocations')),
                ('laboratory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorlaboratory_laboratory_id', to='medicify_project.tbllaboratory')),
            ],
            options={
                'db_table': 'tblDoctorLaboratorylink',
            },
        ),
        migrations.CreateModel(
            name='tblPrescribeLaboratory',
            fields=[
                ('prescribelaboratory_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('laboratory_status', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionlaboratory_doctor_id', to='medicify_project.tbldoctors')),
                ('laboratory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionlaboratory_laboratory_id', to='medicify_project.tbllaboratory')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionlaboratory_patient_id', to='medicify_project.tblpatients')),
                ('prescription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionlaboratory_prescription_id', to='medicify_project.tblprescriptions')),
            ],
            options={
                'db_table': 'tblPrescribeLaboratory',
            },
        ),
    ]
