# Generated by Django 5.0.1 on 2024-10-22 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0039_tbllaboratory_tbldoctorlaboratorylink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblDealPublish',
            fields=[
                ('DealPublish_id', models.AutoField(primary_key=True, serialize=False)),
                ('PublishedOn', models.BigIntegerField(blank=True, null=True)),
                ('ExpiryOn', models.BigIntegerField(blank=True, null=True)),
                ('PaymentDetails', models.IntegerField(blank=True, null=True)),
                ('DealStatus', models.IntegerField(default=1)),
                ('DeleteReason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblDealPublish',
            },
        ),
        migrations.CreateModel(
            name='tblDeals',
            fields=[
                ('Deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(blank=True, max_length=255, null=True)),
                ('DealOwnerMobileNo', models.CharField(blank=True, max_length=15, null=True)),
                ('DealOwnerPersonName', models.CharField(blank=True, max_length=255, null=True)),
                ('DealMedicalNonMedical', models.IntegerField(default=1)),
                ('DealTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('DealKeywords', models.TextField(blank=True, null=True)),
                ('DealContentType', models.IntegerField(default=1)),
                ('DealContentURL_forWeb', models.CharField(blank=True, max_length=255, null=True)),
                ('DealContentURL_forMobile', models.CharField(blank=True, max_length=255, null=True)),
                ('DealWebsiteURL', models.CharField(blank=True, max_length=255, null=True)),
                ('Show_to_Doctor', models.IntegerField(default=1)),
                ('Show_to_Pharmacy', models.IntegerField(default=1)),
                ('Show_to_Labs', models.IntegerField(default=1)),
                ('DealStatus', models.IntegerField(default=1)),
                ('DealViews', models.IntegerField(default=0)),
                ('DealLikes', models.IntegerField(default=0)),
                ('DealInterests', models.IntegerField(default=0)),
                ('DealClicks', models.IntegerField(default=0)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblDeals',
            },
        ),
        migrations.CreateModel(
            name='tblDealsCategories',
            fields=[
                ('DealCategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(blank=True, max_length=255, null=True)),
                ('CategoryMedicalNonMedical', models.IntegerField(blank=True, null=True)),
                ('CategoryKewords', models.TextField(blank=True, null=True)),
                ('CategoryStatus', models.IntegerField(default=1)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblDealsCategories',
            },
        ),
        migrations.CreateModel(
            name='tblDealActionRecorder',
            fields=[
                ('DealAction_id', models.AutoField(primary_key=True, serialize=False)),
                ('DealActionType', models.IntegerField()),
                ('DealActionDateTime', models.BigIntegerField(blank=True, null=True)),
                ('DealActionUser_id', models.IntegerField(blank=True, null=True)),
                ('DealActionUser_type', models.IntegerField(blank=True, null=True)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('DealPublish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tblDealActionRecorder_DealPublish_id', to='medicify_project.tbldealpublish')),
            ],
            options={
                'db_table': 'tblDealActionRecorder',
            },
        ),
        migrations.AddField(
            model_name='tbldealpublish',
            name='Deal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tblDealPublish_Deal_id', to='medicify_project.tbldeals'),
        ),
        migrations.AddField(
            model_name='tbldeals',
            name='DealCategory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tblDeal_DealCategory_id', to='medicify_project.tbldealscategories'),
        ),
    ]
