# Generated by Django 5.0.1 on 2024-10-22 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0040_tbldealpublish_tbldeals_tbldealscategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldealpublish',
            name='PaymentDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='tblDealCategoryLink',
            fields=[
                ('DealCategorylink_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('DealCategory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tblDealCategoryLink_DealCategory_id', to='medicify_project.tbldealscategories')),
                ('DealPublish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tblDealCategoryLink_DealPublish_id', to='medicify_project.tbldealpublish')),
                ('Deal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tblDealCategoryLink_Deal_id', to='medicify_project.tbldeals')),
            ],
            options={
                'db_table': 'tblDealCategoryLink',
            },
        ),
    ]
