# Generated by Django 5.0.1 on 2024-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicify_project', '0041_alter_tbldealpublish_paymentdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldealactionrecorder',
            name='DealInterest',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tbldealactionrecorder',
            name='DealLike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tbldealactionrecorder',
            name='DealShare',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
